### ISSUE TITLE
Error in text_recognition.py

### ISSUE THREAD

**Issue by tanujdhiman** [rssr25/Computer-Vision#1]
I am running this file !(https://github.com/rssr25/Computer-Vision/blob/master/18.%20OCR%20with%20Teserract/text_recognition.py)

The error I am facing in line 83.
Error is "NonType" has no attribute "copy"

Thanks.

**Comment by rssr25** [comment]
The "image" comes from the args which is parsed by the argparse library. While running the file from the CMD please check if you're adding the --image attribute or not. NoneType will come when there is no object in the "image".

**Comment by tanujdhiman** [comment]
Thanks for clarifying my doubt.
